name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23li0CPECg87hkOb0T"
GITHUB_OWNER = "wanai2024"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.clashare.org/api/auth"
NEXT_PUBLIC_API_URL="https://nav.clashare.org"

